name: security_guard_mx
description: "Security guard management application. Allows supervisors to create checkpoints and routes, while guards can scan QR codes during rounds and report incidents in real time."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
